import Link from "next/link";

export const metadata = {
  title: "Terms of Service",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black px-4 py-12 text-slate-300">
      <div className="mx-auto max-w-3xl">
        <Link href="/" className="text-sm text-blue-400 hover:text-blue-300">
          Back to home
        </Link>

        <h1 className="mt-6 text-2xl font-semibold text-slate-50">Terms of Service</h1>
        <p className="mt-2 text-sm text-slate-500">Last updated: July 9, 2026</p>

        <div className="mt-8 space-y-8 text-sm leading-relaxed">
          <section>
            <p>
              These Terms of Service (&ldquo;Terms&rdquo;) govern access to and use of AIBOS
              (the &ldquo;Service&rdquo;), operated by [Company Legal Name] (&ldquo;we,&rdquo;
              &ldquo;us,&rdquo; or &ldquo;the Company&rdquo;). By creating an account or otherwise
              using the Service, you agree to be bound by these Terms. If you do not agree, do not
              use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-50">1. The Service</h2>
            <p className="mt-2">
              AIBOS is a multi tenant business management platform that provides tools
              including customer relationship management, sales, inventory, procurement,
              invoicing, accounting, human resources, payroll, project management, a shared
              calendar, support ticketing, marketing campaign tracking, workflow automation, third
              party integrations, and an AI assistant. Each customer&apos;s account and data are
              organized into a separate company workspace.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-50">2. Accounts</h2>
            <p className="mt-2">
              You must provide accurate information when creating an account and are responsible
              for maintaining the confidentiality of your login credentials and for all activity
              that occurs under your account. You must notify us promptly of any unauthorized use
              of your account. The person who registers a company workspace and any users they
              invite are jointly responsible for how that workspace is used.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-50">3. Your Data</h2>
            <p className="mt-2">
              You retain ownership of all data you enter into the Service, including customer
              records, financial data, employee and payroll information, and documents you upload
              (your &ldquo;Customer Data&rdquo;). You grant us a license to host, process, and
              transmit
              Customer Data solely for the purpose of operating and supporting the Service on
              your behalf. We will not sell your Customer Data or use it to train models for any
              customer other than you.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-50">4. AI Features</h2>
            <p className="mt-2">
              The Service includes an AI assistant powered by a third party language model
              provider. Responses generated by the assistant may be inaccurate, incomplete, or
              unsuitable for your specific situation. AI generated output is provided for
              convenience only and does not constitute financial, legal, tax, or accounting
              advice. You are responsible for reviewing and verifying any AI generated content
              before relying on it, particularly content related to payroll, accounting, or
              customer communications.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-50">5. Fees and Subscriptions</h2>
            <p className="mt-2">
              Certain features or plans may require payment of fees, which will be described to
              you at the time of purchase. Fees are non refundable except as required by law or as
              expressly stated at the time of purchase. We may change our fees on a going forward
              basis with reasonable advance notice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-50">6. Acceptable Use</h2>
            <p className="mt-2">
              You agree not to use the Service to store or transmit unlawful content, to attempt
              to gain unauthorized access to any system or data, to interfere with the operation
              of the Service, or to use the Service in a way that violates the rights of any third
              party.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-50">7. Third Party Services</h2>
            <p className="mt-2">
              The Service relies on third party providers to operate, including infrastructure
              hosting, a managed database, transactional email delivery, and, if you choose to
              connect it, your Gmail account. Your use of those integrations is also subject to
              the applicable third party&apos;s own terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-50">8. Termination</h2>
            <p className="mt-2">
              You may stop using the Service and request deletion of your workspace at any time.
              We may suspend or terminate access to the Service if you violate these Terms, and we
              will make reasonable efforts to give you notice and an opportunity to export your
              Customer Data before deletion, except where immediate action is required to protect
              the Service or other users.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-50">9. Disclaimer of Warranties</h2>
            <p className="mt-2">
              The Service is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without
              warranties of any kind,
              whether express or implied, including warranties of merchantability, fitness for a
              particular purpose, and non infringement. We do not warrant that the Service will be
              uninterrupted, secure, or error free.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-50">10. Limitation of Liability</h2>
            <p className="mt-2">
              To the maximum extent permitted by law, the Company will not be liable for any
              indirect, incidental, special, consequential, or punitive damages, or for any loss
              of profits, revenue, data, or goodwill, arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-50">11. Changes to These Terms</h2>
            <p className="mt-2">
              We may update these Terms from time to time. If we make material changes, we will
              provide notice, such as by posting an update within the Service or contacting the
              account owner directly. Continued use of the Service after a change takes effect
              constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-50">12. Governing Law</h2>
            <p className="mt-2">
              These Terms are governed by the laws of [Jurisdiction], without regard to its
              conflict of laws principles.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-slate-50">13. Contact</h2>
            <p className="mt-2">
              Questions about these Terms can be sent to [Contact Email].
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
