const MESSAGES: Record<string, string> = {
  forbidden: "You don't have permission to perform that action.",
  "in-use": "This record can't be deleted because it's referenced elsewhere.",
  invalid: "Please check the form for errors and try again.",
  "order-delete-blocked": "Only pending or cancelled orders can be deleted. Cancel the order first, which puts any shipped stock back.",
  "order-invoice-blocked": "This order can't be invoiced yet. Confirm it, add items, and check it has no invoice already.",
  confirm: "The confirmation text didn't match. Nothing was deleted.",
  "no-email": "This customer doesn't have an email address on file, so the invoice couldn't be sent.",
  "send-failed": "The invoice couldn't be sent. Check your email configuration and try again.",
  "last-owner": "You can't remove the last owner of a company.",
  "returns-disabled": "Returns are turned off for this company. Turn them on in the return policy.",
  "not-returnable": "Only fulfilled orders can be returned.",
  "return-window": "This order is outside the return window set in your return policy.",
  "return-qty": "That quantity is more than can still be returned for this item.",
  "return-locked": "This return can no longer be changed because the goods have already been received.",
  "return-empty": "Add at least one item before moving this return forward.",
  "mrp-disabled": "Planning is turned off for this company. Turn it on in the planning settings.",
  "bom-cycle": "That component already uses this product, so adding it would create a loop.",
  "not-made": "Only products with a bill of materials can be made. Add components to the product first.",
  "component-short": "Not enough components in stock to complete this work order.",
  "work-order-locked": "A completed work order can't be deleted because it has already moved stock.",
  "plan-changed": "The plan changed since this page loaded. Here is the latest version.",
  "no-supplier": "Set a preferred supplier on the product before creating a purchase order for it.",
  "edi-setup": "Set up your EDI identity in the EDI settings first.",
  "edi-no-partner": "No enabled trading partner is set up to receive this document.",
  "edi-separators": "Separators must each be one symbol, all different, and not a letter, digit or space.",
  "edi-duplicate-partner": "A trading partner with that qualifier and ID already exists.",
  "edi-empty": "Add at least one line before generating an EDI document.",
  "edi-not-shipped": "A ship notice can only be sent once the order is fulfilled.",
  "edi-too-large": "EDI files can be at most 1MB.",
  "co-duplicate": "A cost center with that code already exists.",
  "branch-duplicate": "A branch with that code already exists.",
  "branch-main": "The main branch can't be deactivated. Make another branch the main one first.",
  "branch-limit": "Your plan has no room for another active branch. Deactivate one, or ask the owner to move to a bigger plan on the Billing page.",
  "billing-unavailable": "Billing couldn't reach Stripe just now. Nothing was charged. Please try again in a few minutes.",
  "activity-invalid": "Write what happened before saving the activity.",
  "followup-invalid": "Give the reminder a title and a due date.",
  "account-name": "Your name must be 2 to 100 characters.",
  "account-password-short": "Your new password must be at least 8 characters.",
  "account-password-mismatch": "The new passwords don't match. Type the same password twice.",
  "account-password-wrong": "Your current password isn't right. Nothing was changed.",
  "account-password-same": "Choose a password different from your current one.",
  "account-rate": "Too many attempts. Wait 15 minutes, then try again.",
  "plan-no-extra-users": "That plan has a fixed number of users and your team, counting open invites, is bigger. Choose Starter or above, or make room first.",
  "plan-not-on-sale": "That plan isn't sold online any more. Choose Starter or Growth, or contact sales about Enterprise.",
  "enterprise-users": "Your team, counting open invites, is bigger than the users you chose. Choose at least as many users as people.",
  "enterprise-branches": "You have more active branches than you chose. Choose at least as many branches, or deactivate some first.",
  "plan-price-missing": "That plan isn't available for checkout yet. Please try again later.",
  "plan-too-small-users": "Your team, counting open invites, is bigger than any plan takes (150 users). Ask us about an Enterprise plan.",
  "plan-too-small-branches": "You have more active branches than that plan allows. Deactivate branches first.",
  "plan-already-subscribed": "You already have a subscription. Choose a plan below to change it instead.",
  "plan-not-active": "Plan changes need an active subscription. Subscribe first, or update your payment method.",
  "plan-same": "You're already on that plan and billing period.",
  "branch-inactive": "That branch is inactive. Reactivate it on the Branches page first.",
  "approval-needed": "This was suggested by an automation, so an owner or admin has to approve it first.",
  "transfer-same-branch": "Choose two different branches to move stock between.",
  "transfer-locked": "This transfer has already been sent, so it can't be changed.",
  "transfer-empty": "Add at least one product before sending.",
  "transfer-changed": "This transfer or its stock changed while you were working. Check it and try again.",
  "co-in-use": "This cost center has carried costs or employees, so it can't be deleted. Mark it inactive instead.",
  "co-settled": "This internal order is already settled and can't be changed.",
  "co-no-receiver": "Choose a cost center to settle to before settling this order.",
  "co-shares": "Receivers must be different from the sender, each listed once, with shares adding up to 100%.",
  "co-already-run": "This allocation has already run for that month. Reverse that run first to run it again.",
  "lots-needed": "This order has lot or serial tracked products. Enter their lot numbers or serials to receive it.",
  "lot-short": "Not enough usable lots of a tracked component to complete this. Expired lots may be blocked in inventory settings.",
  "quote-locked": "This quote has been accepted or declined, so it can't be changed. Copy it to a new quote instead.",
  "quote-empty": "Add at least one product before sending the quote.",
  "quote-no-email": "This customer has no email address on file. Add one on the customer page first.",
  "quote-send-failed": "The quote couldn't be emailed. Check your email setup and try again.",
  "quote-cannot-accept": "This quote can't be accepted right now. It needs products and must not be expired or already decided.",
  "whatsapp-code": "Enter the country code as 1 to 4 digits, for example 27.",
  "custom-field-invalid": "One of the custom fields has a value it can't take. Check numbers, dates and dropdown choices.",
  "tag-invalid": "Give the tag a name of up to 40 characters.",
  "tag-duplicate": "A tag with that name already exists.",
  "tag-limit": "You can have up to 30 tags. Remove one you no longer use first.",
  "field-invalid": "Give the field a name of up to 60 characters and choose its type.",
  "field-options": "A dropdown list needs at least two choices, one per line.",
  "field-limit": "You can have up to 20 custom fields. Remove one you no longer use first.",
  "mail-not-connected": "Connect a Google account on the Integrations page first.",
  "mail-no-permission": "Your Google account was connected without permission to read mail. Reconnect it below to allow email logging.",
  "mail-plan": "Email logging comes with the Integrations on the Starter plan and up.",
  "mail-error": "Gmail couldn't be read just now. Try again in a few minutes, or reconnect your Google account.",
  "merge-changed": "Those customers changed while you were looking. Here is the latest list.",
  "sequence-empty": "Add at least one email before turning the sequence on.",
  "sequence-full": "A sequence can have up to 10 emails.",
  "step-invalid": "Each email needs a subject, a message, and a wait of 0 to 90 days.",
  "enroll-skipped": "They weren't added: they need an email address, mustn't have unsubscribed, and mustn't be in that sequence already.",
  "co-nothing": "The sender cost center has no cost in that month, so there is nothing to allocate.",
};

export function ErrorBanner({ code }: { code?: string }) {
  if (!code || !MESSAGES[code]) return null;
  return (
    <p className="mb-4 rounded-md border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-400">
      {MESSAGES[code]}
    </p>
  );
}
